export const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL;
export const NEXT_PUBLIC_SANITY_TOKEN =
    process.env.NEXT_PUBLIC_SANITY_TOKEN;
export const NEXT_TWILIO_SID = process.env.NEXT_TWILIO_SID;
export const NEXT_TWILIO_AUTH_TOKEN = process.env.NEXT_TWILIO_AUTH_TOKEN;
export const NEXT_TWILIO_MESSAGE_SERVICE_SID = process.env.NEXT_TWILIO_MESSAGE_SERVICE_SID;